{{- if .Values.database.postgres.bundled.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kagent.passwordSecretName" . }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  POSTGRES_PASSWORD: {{ "kagent" | b64enc | quote }}
{{- end }}
