apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kagent.fullname" . }}-ui-config
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- tpl (.Files.Get "files/nginx.conf") . | nindent 4 }}
  supervisord.conf: |
    {{- tpl (.Files.Get "files/supervisord.conf") . | nindent 4 }}
