apiVersion: v1
kind: Service
metadata:
  name: {{ include "kagent.fullname" . }}-ui
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.ui.labels" . | nindent 4 }}
  {{- with .Values.ui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.ports.port }}
      targetPort: {{ .Values.ui.service.ports.targetPort }}
      protocol: TCP
      name: ui
  selector:
    {{- include "kagent.ui.selectorLabels" . | nindent 4 }}
