#!/bin/bash
set -euo pipefail

# OS 安装脚本 — 将 Live rootfs 写入目标磁盘
# 被 TUI installer 的 DeployEngine 调用（step_id: os-install）
#
# 流程: 分区 → 格式化 → unsquashfs → fstab → GRUB → chroot 配置 → 状态标记

LOG_TAG="[os-install]"

# ── 参数读取 ──
# install-state.json 由 TUI config_generator 生成
STATE_FILE="/etc/vdi/install-state.json"
if [ ! -f "$STATE_FILE" ]; then
    echo "$LOG_TAG 错误: 找不到 $STATE_FILE" >&2
    exit 1
fi

DISK=$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['config']['install_disk'])")
SCHEME=$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['config'].get('partition_scheme', 'auto'))")
SWAP_SIZE=$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['config'].get('swap_size', '8G'))")
HOSTNAME=$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['config'].get('hostname', 'vdi-node-01'))")

TARGET="/mnt/target"

echo "$LOG_TAG 磁盘: $DISK  方案: $SCHEME  Swap: $SWAP_SIZE  主机名: $HOSTNAME"

# ── 安全检查 ──
if [ ! -b "$DISK" ]; then
    echo "$LOG_TAG 错误: $DISK 不是块设备" >&2
    exit 1
fi

# 不允许安装在 Live 介质所在设备
LIVE_DEV=$(lsblk -no PKNAME /cdrom 2>/dev/null || true)
if [ -n "$LIVE_DEV" ] && [ "/dev/$LIVE_DEV" = "$DISK" ]; then
    echo "$LOG_TAG 错误: 不能将系统安装到 Live 介质设备 $DISK" >&2
    exit 1
fi

# ── 1. 分区 ──
echo "$LOG_TAG 开始分区..."

# 确保旧分区未挂载
umount -R "$TARGET" 2>/dev/null || true
swapoff "${DISK}"* 2>/dev/null || true

# sgdisk 全新分区表（GPT）
sgdisk --zap-all "$DISK" 2>/dev/null || true

if [ "$SCHEME" = "auto" ] && [ "$SWAP_SIZE" != "0" ]; then
    # Auto: EFI(512M) + swap + root(rest)
    sgdisk -n 1:0:+512M -t 1:ef00 -c 1:"EFI System" "$DISK"
    sgdisk -n 2:0:+${SWAP_SIZE} -t 2:8200 -c 2:"Linux Swap" "$DISK"
    sgdisk -n 3:0:0 -t 3:8300 -c 3:"Linux Root" "$DISK"
    EFI_PART="${DISK}1"
    SWAP_PART="${DISK}2"
    ROOT_PART="${DISK}3"
else
    # Minimal: EFI(512M) + root(rest)
    sgdisk -n 1:0:+512M -t 1:ef00 -c 1:"EFI System" "$DISK"
    sgdisk -n 2:0:0 -t 2:8300 -c 2:"Linux Root" "$DISK"
    EFI_PART="${DISK}1"
    SWAP_PART=""
    ROOT_PART="${DISK}2"
fi

# 等待分区设备节点就绪
partprobe "$DISK" 2>/dev/null || true
sleep 2

echo "$LOG_TAG 分区完成: EFI=$EFI_PART ROOT=$ROOT_PART SWAP=$SWAP_PART"

# ── 2. 格式化 ──
echo "$LOG_TAG 格式化分区..."
mkfs.vfat -F 32 "$EFI_PART"
if [ -n "$SWAP_PART" ]; then
    mkswap "$SWAP_PART"
fi
mkfs.ext4 -F -q "$ROOT_PART"
echo "$LOG_TAG 格式化完成"

# ── 3. 挂载 ──
echo "$LOG_TAG 挂载分区..."
mkdir -p "$TARGET"
mount "$ROOT_PART" "$TARGET"
mkdir -p "$TARGET/boot/efi"
mount "$EFI_PART" "$TARGET/boot/efi"
if [ -n "$SWAP_PART" ]; then
    swapon "$SWAP_PART"
fi
echo "$LOG_TAG 挂载完成"

# ── 4. 提取 rootfs ──
echo "$LOG_TAG 提取 rootfs 到目标磁盘（此步骤较慢，请耐心等待）..."

SQUASHFS=""
for candidate in /cdrom/casper/filesystem.squashfs \
                  /mnt/iso/casper/filesystem.squashfs \
                  /lib/live/mount/medium/casper/filesystem.squashfs; do
    if [ -f "$candidate" ]; then
        SQUASHFS="$candidate"
        break
    fi
done

if [ -z "$SQUASHFS" ]; then
    echo "$LOG_TAG 错误: 找不到 filesystem.squashfs" >&2
    umount -R "$TARGET" 2>/dev/null || true
    exit 1
fi

unsquashfs -d "$TARGET" "$SQUASHFS"
echo "$LOG_TAG rootfs 提取完成"

# ── 5. 生成 fstab ──
echo "$LOG_TAG 生成 /etc/fstab..."

ROOT_UUID=$(blkid -s UUID -o value "$ROOT_PART")
EFI_UUID=$(blkid -s UUID -o value "$EFI_PART")

FSTAB="/etc/fstab"
cat > "$TARGET$FSTAB" <<EOF
# /etc/fstab: static file system information — generated by VDI installer
UUID=$ROOT_UUID  /          ext4  errors=remount-ro  0  1
UUID=$EFI_UUID   /boot/efi  vfat  umask=0077         0  2
EOF

if [ -n "$SWAP_PART" ]; then
    SWAP_UUID=$(blkid -s UUID -o value "$SWAP_PART")
    echo "UUID=$SWAP_UUID  none  swap  sw  0  0" >> "$TARGET$FSTAB"
fi

echo "$LOG_TAG fstab 已生成"

# ── 6. 安装 GRUB ──
echo "$LOG_TAG 安装引导器 (GRUB)..."

# 绑定挂载（chroot 需要）
mount --bind /dev "$TARGET/dev"
mount --bind /dev/pts "$TARGET/dev/pts"
mount --bind /proc "$TARGET/proc"
mount --bind /sys "$TARGET/sys"
mount --bind /run "$TARGET/run"

# 确保 /cdrom 可用于 chroot 内的离线源
if [ -d /cdrom ]; then
    mkdir -p "$TARGET/cdrom"
    mount --bind /cdrom "$TARGET/cdrom" 2>/dev/null || true
fi

chroot "$TARGET" grub-install --target=x86_64-efi \
    --efi-directory=/boot/efi \
    --bootloader-id=VDI \
    --recheck --no-nvram 2>/dev/null || true

chroot "$TARGET" grub-install --target=i386-pc \
    "$DISK" 2>/dev/null || true

chroot "$TARGET" update-grub 2>/dev/null || true

echo "$LOG_TAG GRUB 安装完成"

# ── 7. Chroot 系统配置 ──
echo "$LOG_TAG 配置目标系统..."

# 主机名
echo "$HOSTNAME" > "$TARGET/etc/hostname"
cat > "$TARGET/etc/hosts" <<EOF
127.0.0.1 localhost
127.0.1.1 $HOSTNAME

::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

# 网络 — DHCP 自动获取（安装后首次启动自行获取 IP）
mkdir -p "$TARGET/etc/netplan"
cat > "$TARGET/etc/netplan/01-eth.yaml" <<EOF
network:
  version: 2
  ethernets:
    id0:
      match:
        name: "en*"
      dhcp4: true
EOF

# root 密码（与 Live 一致，部署后可修改）
echo "root:vdi" | chroot "$TARGET" chpasswd

# 允许 root SSH 登录
sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' "$TARGET/etc/ssh/sshd_config" 2>/dev/null || true
sed -i 's/#PasswordAuthentication.*/PasswordAuthentication yes/' "$TARGET/etc/ssh/sshd_config" 2>/dev/null || true

# 启用 systemd 服务
chroot "$TARGET" systemctl enable ssh 2>/dev/null || true
chroot "$TARGET" systemctl enable systemd-networkd 2>/dev/null || true

# 更新 initramfs（适配目标硬件）
chroot "$TARGET" update-initramfs -u -k all 2>/dev/null || true

echo "$LOG_TAG 目标系统配置完成"

# ── 8. 写入装机状态标记 ──
echo "$LOG_TAG 写入装机状态标记..."
mkdir -p "$TARGET/etc/vdi"

python3 -c "
import json
state = json.load(open('$STATE_FILE'))
state['phase'] = 'os-installed'
json.dump(state, open('$TARGET/etc/vdi/install-state.json', 'w'), indent=2)
"

# 安装续跑 hook：硬盘启动后自动恢复 TUI 部署流程
cat > "$TARGET/etc/profile.d/vdi-resume.sh" <<'RESUME'
#!/bin/bash
# VDI 部署续跑 — 硬盘启动后自动恢复部署流程
if [ -n "$PS1" ] && [ "$(id -u)" -eq 0 ]; then
    STATE="/etc/vdi/install-state.json"
    if [ -f "$STATE" ]; then
        PHASE=$(python3 -c "import json; print(json.load(open('$STATE')).get('phase',''))" 2>/dev/null || true)
        if [ "$PHASE" = "os-installed" ]; then
            CURRENT_TTY="$(tty 2>/dev/null)"
            if [ "$CURRENT_TTY" = "/dev/tty1" ]; then
                export TERM="${TERM:-linux}"
                echo "[vdi-resume] 检测到装机完成，恢复部署流程..."
                python3 /opt/vdi/tui/installer.py
                echo "[vdi-resume] TUI 已退出，可手动重启: python3 /opt/vdi/tui/installer.py"
            fi
        fi
    fi
fi
RESUME
chmod +x "$TARGET/etc/profile.d/vdi-resume.sh"

# 复制 TUI 和部署脚本到目标系统
mkdir -p "$TARGET/opt/vdi"
if [ -d /opt/vdi/tui ]; then
    rm -rf "$TARGET/opt/vdi/tui"
    cp -a /opt/vdi/tui "$TARGET/opt/vdi/tui"
fi
if [ -d /opt/vdi/deploy ]; then
    rm -rf "$TARGET/opt/vdi/deploy"
    cp -a /opt/vdi/deploy "$TARGET/opt/vdi/deploy"
fi
# 复制 TUI 生成的配置
if [ -d /etc/vdi ]; then
    cp -a /etc/vdi/* "$TARGET/etc/vdi/" 2>/dev/null || true
fi

echo "$LOG_TAG 装机状态标记已写入"

# ── 9. 卸载 ──
echo "$LOG_TAG 卸载分区..."
umount "$TARGET/cdrom" 2>/dev/null || true
umount "$TARGET/run" 2>/dev/null || true
umount "$TARGET/sys" 2>/dev/null || true
umount "$TARGET/proc" 2>/dev/null || true
umount "$TARGET/dev/pts" 2>/dev/null || true
umount "$TARGET/dev" 2>/dev/null || true
if [ -n "$SWAP_PART" ]; then
    swapoff "$SWAP_PART" 2>/dev/null || true
fi
umount "$TARGET/boot/efi" 2>/dev/null || true
umount "$TARGET" 2>/dev/null || true

echo "$LOG_TAG OS 安装完成！移除 CD-ROM 后重启即可从硬盘引导。"
