apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: currency-converter-agent
spec:
  description: A currency converter LangGraph agent that can convert currencies
  type: BYO
  byo:
    deployment:
      image: localhost:5001/langgraph-currency:latest
      env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: kagent-openai
              key: OPENAI_API_KEY
        # Enable OpenTelemetry tracing, make sure to set this according to your environment
        - name: OTEL_TRACING_ENABLED
          value: "true"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://jaeger-collector.jaeger.svc.cluster.local:4317"
        - name: LANGSMITH_TRACING
          value: "true"
        - name: LANGSMITH_OTEL_ENABLED
          value: "true"
        - name: LANGSMITH_ENDPOINT
          value: "http://jaeger-collector.jaeger.svc.cluster.local:4317"
        - name: LANGSMITH_API_KEY
          value: "langsmith-api-key"
        - name: LANGSMITH_WORKSPACE_ID
          value: "kagent-langgraph"
