package mcp

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	commonexec "github.com/kagent-dev/kagent/go/core/cli/internal/common/exec"
	commonk8s "github.com/kagent-dev/kagent/go/core/cli/internal/common/k8s"
	"github.com/kagent-dev/kagent/go/core/cli/internal/config"
	"github.com/kagent-dev/kagent/go/core/cli/internal/mcp/manifests"
	"github.com/kagent-dev/kmcp/api/v1alpha1"
)

const (
	transportHTTP  = "http"
	transportStdio = "stdio"
)

// DeployCfg contains configuration for MCP deploy command
type DeployCfg struct {
	Namespace   string
	DryRun      bool
	Output      string
	Image       string
	Transport   string
	Port        int
	Command     string
	Args        []string
	Env         []string
	Force       bool
	File        string
	Environment string
	NoInspector bool
	// Package subcommand specific
	PackageManager string
	PackageName    string
	PackageSecrets []string
}

func PackageDeployMcp(cfg *DeployCfg) error {
	// Validate package manager
	if cfg.PackageManager != "npx" && cfg.PackageManager != "uvx" {
		return fmt.Errorf("unsupported package manager: %s (must be 'npx' or 'uvx')", cfg.PackageManager)
	}

	// Validate args
	if len(cfg.Args) == 0 {
		return fmt.Errorf("args are required (e.g., --args package-name)")
	}

	// Parse environment variables
	envMap := parseEnvVars(cfg.Env)

	// Convert secret names to ObjectReferences
	secretRefs := make([]corev1.LocalObjectReference, 0, len(cfg.PackageSecrets))
	for _, secretName := range cfg.PackageSecrets {
		secretRefs = append(secretRefs, corev1.LocalObjectReference{
			Name: secretName,
		})
	}

	// Set default port if none specified
	port := 3000
	if cfg.Port != 0 {
		port = cfg.Port
	}

	// Create MCPServer for package deployment
	mcpServer := &v1alpha1.MCPServer{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "kagent.dev/v1alpha1",
			Kind:       "MCPServer",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      cfg.PackageName,
			Namespace: cfg.Namespace,
		},
		Spec: v1alpha1.MCPServerSpec{
			Deployment: v1alpha1.MCPServerDeployment{
				Image:      cfg.Image,
				Port:       uint16(port),
				Cmd:        cfg.PackageManager,
				Args:       cfg.Args,
				Env:        envMap,
				SecretRefs: secretRefs,
			},
			TransportType: getTransportType(cfg),
		},
	}

	// Configure transport-specific settings
	if mcpServer.Spec.TransportType == v1alpha1.TransportTypeHTTP {
		mcpServer.Spec.HTTPTransport = &v1alpha1.HTTPTransport{
			TargetPort: uint32(port),
			TargetPath: "/mcp",
		}
	} else {
		mcpServer.Spec.StdioTransport = &v1alpha1.StdioTransport{}
	}

	// Convert MCPServer to YAML
	mcpServerYAML, err := yaml.Marshal(mcpServer)
	if err != nil {
		return fmt.Errorf("failed to marshal MCPServer to YAML: %w", err)
	}

	// Create YAML content with header
	yamlContent := fmt.Sprintf(
		"# MCPServer deployment generated by kagent mcp deploy package cmd\n# Deployment: %s\n# Manager: %s\n# Args: %v\n%s",
		cfg.PackageName,
		cfg.PackageManager,
		cfg.Args,
		string(mcpServerYAML),
	)

	// Handle output
	if cfg.Output != "" {
		// Write to file
		if err := os.WriteFile(cfg.Output, []byte(yamlContent), 0644); err != nil {
			return fmt.Errorf("failed to write to file: %w", err)
		}
		fmt.Printf("✅ MCPServer manifest written to: %s\n", cfg.Output)
	}

	if cfg.DryRun {
		// Print to stdout
		fmt.Print(yamlContent)
	} else {
		// Apply MCPServer to cluster
		if err := applyToCluster(cfg, "", yamlContent, mcpServer); err != nil {
			return fmt.Errorf("failed to apply to cluster: %w", err)
		}
	}

	return nil
}

// getTransportType determines the transport type based on flags
func getTransportType(cfg *DeployCfg) v1alpha1.TransportType {
	if cfg.Transport != "" {
		switch cfg.Transport {
		case transportHTTP:
			return v1alpha1.TransportTypeHTTP
		case transportStdio:
			return v1alpha1.TransportTypeStdio
		default:
			// Default to stdio for package deployments
			return v1alpha1.TransportTypeStdio
		}
	}
	// Default to stdio for package deployments
	return v1alpha1.TransportTypeStdio
}

func DeployMcp(cfg *DeployCfg) error {
	// Determine project directory
	var projectDir string
	var err error

	appCfg, err := config.Get()
	if err != nil {
		return fmt.Errorf("failed to get config: %w", err)
	}

	if cfg.File != "" {
		// Use specified file path
		projectDir, err = getProjectDirFromFile(cfg.File)
		if err != nil {
			return fmt.Errorf("failed to get project directory from file: %w", err)
		}
	} else {
		// Use current working directory
		projectDir, err = os.Getwd()
		if err != nil {
			return fmt.Errorf("failed to get current directory: %w", err)
		}
	}

	// Load project manifest
	manifestManager := manifests.NewManager(projectDir)
	if !manifestManager.Exists() {
		return fmt.Errorf("manifest.yaml not found in %s. Run 'kagent mcp init' first or specify a valid path with --file", projectDir)
	}

	projectManifest, err := manifestManager.Load()
	if err != nil {
		return fmt.Errorf("failed to load project manifest: %w", err)
	}

	// Determine deployment name
	deploymentName := projectManifest.Name

	// Generate MCPServer resource
	mcpServer, err := generateMCPServer(cfg, projectManifest, deploymentName, cfg.Environment)
	if err != nil {
		return fmt.Errorf("failed to generate MCPServer: %w", err)
	}

	// Set namespace
	mcpServer.Namespace = cfg.Namespace

	if appCfg.Verbose {
		fmt.Printf("Generated MCPServer: %s/%s\n", mcpServer.Namespace, mcpServer.Name)
	}

	// Convert MCPServer to YAML
	mcpServerYAML, err := yaml.Marshal(mcpServer)
	if err != nil {
		return fmt.Errorf("failed to marshal MCPServer to YAML: %w", err)
	}

	// Create YAML content with header
	yamlContent := fmt.Sprintf(
		"# MCPServer deployment generated by kagent mcp deploy cmd\n# Project: %s\n# Framework: %s\n%s",
		projectManifest.Name,
		projectManifest.Framework,
		string(mcpServerYAML),
	)

	// Handle output
	if cfg.Output != "" {
		// Write to file
		if err := os.WriteFile(cfg.Output, []byte(yamlContent), 0644); err != nil {
			return fmt.Errorf("failed to write to file: %w", err)
		}
		fmt.Printf("✅ MCPServer manifest written to: %s\n", cfg.Output)
	}

	if cfg.DryRun {
		// Print to stdout
		fmt.Print(yamlContent)
	} else {
		// Apply MCPServer to cluster
		if err := applyToCluster(cfg, projectDir, yamlContent, mcpServer); err != nil {
			return fmt.Errorf("failed to apply to cluster: %w", err)
		}
	}

	return nil
}

// getProjectDirFromFile extracts the project directory from a file path
func getProjectDirFromFile(filePath string) (string, error) {
	// Get absolute path of the file
	absPath, err := filepath.Abs(filePath)
	if err != nil {
		return "", fmt.Errorf("failed to get absolute path: %w", err)
	}

	// Get the directory containing the file
	projectDir := filepath.Dir(absPath)

	// Verify the file exists
	if _, err := os.Stat(absPath); os.IsNotExist(err) {
		return "", fmt.Errorf("file does not exist: %s", absPath)
	}

	return projectDir, nil
}

func generateMCPServer(
	cfg *DeployCfg,
	projectManifest *manifests.ProjectManifest,
	deploymentName,
	environment string,
) (*v1alpha1.MCPServer, error) {
	// Determine image name
	imageName := cfg.Image
	if imageName == "" {
		// Generate default image name
		imageName = fmt.Sprintf("%s:%s",
			strings.ToLower(strings.ReplaceAll(projectManifest.Name, "_", "-")),
			projectManifest.Version,
		)
	}

	// Determine transport type
	transportType := getTransportType(cfg)

	// Determine port
	port := cfg.Port
	if port == 0 {
		port = 3000 // Default port
	}

	// Determine command and args
	command := cfg.Command
	args := cfg.Args
	if command == "" {
		// Set default command based on framework
		command = getDefaultCommand(projectManifest.Framework)
		if len(args) == 0 {
			args = getDefaultArgs(cfg, projectManifest.Framework, port)
		}
	}

	// Parse environment variables
	envVars := parseEnvVars(cfg.Env)

	// Get secret reference from manifest for the specified environment
	secretRef, err := getSecretRefFromManifest(projectManifest, environment)
	if err != nil {
		return nil, fmt.Errorf("failed to get secret reference: %w", err)
	}
	var secretRefs []corev1.LocalObjectReference
	if secretRef != nil {
		secretRefs = append(secretRefs, *secretRef)
	}

	// Create MCPServer spec
	mcpServer := &v1alpha1.MCPServer{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "kagent.dev/v1alpha1",
			Kind:       "MCPServer",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: deploymentName,
			Labels: map[string]string{
				"app.kubernetes.io/name":       deploymentName,
				"app.kubernetes.io/instance":   deploymentName,
				"app.kubernetes.io/component":  "mcp-server",
				"app.kubernetes.io/part-of":    "kagent",
				"app.kubernetes.io/managed-by": "kagent",
				"kagent.dev/framework":         projectManifest.Framework,
				"kagent.dev/version":           sanitizeLabelValue(projectManifest.Version),
			},
			Annotations: map[string]string{
				"kagent.dev/project-name": projectManifest.Name,
				"kagent.dev/description":  projectManifest.Description,
			},
		},
		Spec: v1alpha1.MCPServerSpec{
			Deployment: v1alpha1.MCPServerDeployment{
				Image:      imageName,
				Port:       uint16(port),
				Cmd:        command,
				Args:       args,
				Env:        envVars,
				SecretRefs: secretRefs,
			},
			TransportType: transportType,
		},
	}

	// Configure transport-specific settings
	if transportType == v1alpha1.TransportTypeHTTP {
		mcpServer.Spec.HTTPTransport = &v1alpha1.HTTPTransport{
			TargetPort: uint32(port),
			TargetPath: "/mcp",
		}
	} else {
		mcpServer.Spec.StdioTransport = &v1alpha1.StdioTransport{}
	}

	return mcpServer, nil
}

func getSecretRefFromManifest(
	projectManifest *manifests.ProjectManifest,
	environment string,
) (*corev1.LocalObjectReference, error) {
	if environment == "" {
		return nil, nil // No environment specified
	}

	secretProvider, ok := projectManifest.Secrets[environment]
	if !ok {
		return nil, fmt.Errorf("environment '%s' not found in secrets config", environment)
	}

	if secretProvider.Provider == manifests.SecretProviderKubernetes && secretProvider.Enabled {
		secretName := secretProvider.SecretName
		if secretName == "" {
			return nil, fmt.Errorf("secretName not found in secret provider config for environment %s", environment)
		}

		return &corev1.LocalObjectReference{
			Name: secretName,
		}, nil
	}

	return nil, nil
}

func sanitizeLabelValue(value string) string {
	return strings.ReplaceAll(value, "+", "_")
}

func getDefaultCommand(framework string) string {
	switch framework {
	case manifests.FrameworkFastMCPPython:
		return "python"
	case manifests.FrameworkMCPGo:
		return "./server"
	case manifests.FrameworkTypeScript:
		return "node"
	case manifests.FrameworkJava:
		return "java"
	default:
		return "python"
	}
}

func getDefaultArgs(cfg *DeployCfg, framework string, targetPort int) []string {
	switch framework {
	case manifests.FrameworkFastMCPPython:
		if cfg.Transport == transportHTTP {
			return []string{"src/main.py", "--transport", "http", "--host", "0.0.0.0", "--port", fmt.Sprintf("%d", targetPort)}
		}
		return []string{"src/main.py"}
	case manifests.FrameworkMCPGo:
		return []string{}
	case manifests.FrameworkTypeScript:
		return []string{"dist/index.js"}
	case manifests.FrameworkJava:
		if cfg.Transport == transportHTTP {
			return []string{"-jar", "app.jar", "--transport", "http", "--host", "0.0.0.0", "--port", fmt.Sprintf("%d", targetPort)}
		}
		return []string{"-jar", "app.jar"}
	default:
		return []string{"src/main.py"}
	}
}

func parseEnvVars(envVars []string) map[string]string {
	result := make(map[string]string)
	for _, env := range envVars {
		parts := strings.SplitN(env, "=", 2)
		if len(parts) == 2 {
			result[parts[0]] = parts[1]
		}
	}
	return result
}

func applyToCluster(cfg *DeployCfg, projectDir, yamlContent string, mcpServer *v1alpha1.MCPServer) error {
	appCfg, err := config.Get()
	if err != nil {
		return fmt.Errorf("failed to get config: %w", err)
	}

	// Create kubectl executor with namespace and verbose settings
	kubectl := commonexec.NewKubectlExecutor(appCfg.Verbose, mcpServer.Namespace)

	fmt.Printf("🚀 Applying MCPServer to cluster...\n")

	if err := kubectl.Apply([]byte(yamlContent)); err != nil {
		return err
	}

	fmt.Printf("✅ MCPServer '%s' applied successfully\n", mcpServer.Name)

	// Wait for the deployment to be ready
	fmt.Printf("⌛ Waiting for deployment '%s' to be ready...\n", mcpServer.Name)
	if err := kubectl.WaitForDeployment(mcpServer.Name, 2*time.Minute); err != nil {
		return fmt.Errorf("deployment not ready: %w", err)
	}

	fmt.Printf("✅ Deployment '%s' is ready.\n", mcpServer.Name)
	fmt.Printf("💡 Check status with: kubectl get mcpserver %s -n %s\n", mcpServer.Name, mcpServer.Namespace)
	fmt.Printf("💡 View logs with: kubectl logs -l app.kubernetes.io/name=%s -n %s\n", mcpServer.Name, mcpServer.Namespace)
	if mcpServer.Spec.Deployment.Port != 0 {
		fmt.Printf("💡 Port-forward to the service with: "+
			"kubectl port-forward service/%s %d:%d -n %s\n",
			mcpServer.Name, mcpServer.Spec.Deployment.Port,
			mcpServer.Spec.Deployment.Port, mcpServer.Namespace)
	}

	var configPath string
	if !cfg.NoInspector {
		// Create inspector config
		port := uint16(3000) // default port
		if mcpServer.Spec.Deployment.Port != 0 {
			port = mcpServer.Spec.Deployment.Port
		}
		serverConfig := map[string]any{
			"type": "streamable-http",
			"url":  fmt.Sprintf("http://localhost:%d/mcp", port),
		}
		configPath = filepath.Join(projectDir, "mcp-server-config.json")
		if err := createMCPInspectorConfig(mcpServer.Name, serverConfig, configPath); err != nil {
			return fmt.Errorf("failed to create inspector config: %w", err)
		}

		if err := runInspector(mcpServer, configPath, projectDir); err != nil {
			return fmt.Errorf("failed to run inspector: %w", err)
		}
	}
	return nil
}

func runInspector(mcpServer *v1alpha1.MCPServer, configPath string, projectDir string) error {
	// Check if npx is installed
	if err := checkNpxInstalled(); err != nil {
		return err
	}

	// Start port forwarding in the background
	portForwardCmd, err := runPortForward(mcpServer)
	if err != nil {
		return err
	}
	defer func() {
		if portForwardCmd != nil && portForwardCmd.Process != nil {
			if err := portForwardCmd.Process.Kill(); err != nil {
				fmt.Printf("failed to kill port-forward process: %v\n", err)
			}
		}
	}()

	// Run the inspector
	return runMCPInspector(configPath, mcpServer.Name, projectDir)
}

func runPortForward(mcpServer *v1alpha1.MCPServer) (*exec.Cmd, error) {
	remotePort := mcpServer.Spec.Deployment.Port
	if remotePort == 0 {
		remotePort = 3000 // Default port
	}
	localPort := 3000
	portMapping := fmt.Sprintf("%d:%d", localPort, remotePort)
	args := []string{
		"port-forward",
		"service/" + mcpServer.Name,
		portMapping,
		"-n", mcpServer.Namespace,
	}
	cmd := exec.Command("kubectl", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("failed to start port-forward: %w", err)
	}
	return cmd, nil
}

// GetCurrentNamespace returns the current namespace from kubeconfig for use in root.go
func GetCurrentNamespace() string {
	currentNamespace, err := commonk8s.GetCurrentNamespace()
	if err != nil {
		return "default"
	}
	return currentNamespace
}
