apiVersion: kubekey.kubesphere.io/v1
kind: Inventory
metadata:
  name: vdi-cluster
spec:
  hosts:
    ubuntu-rog:
      connector:
        type: ssh
        host: 192.168.220.128
        port: 22
        user: zcq
        password: "123123"
      internal_ipv4: 192.168.220.128
    ubuntu-rog2:
      connector:
        type: ssh
        host: 192.168.220.129
        port: 22
        user: zcq
        password: "123123"
      internal_ipv4: 192.168.220.129
    ubuntu-rog3:
      connector:
        type: ssh
        host: 192.168.220.130
        port: 22
        user: zcq
        password: "123123"
      internal_ipv4: 192.168.220.130
  groups:
    k8s_cluster:
      groups:
        - kube_control_plane
        - kube_worker
    kube_control_plane:
      hosts:
        - ubuntu-rog
        - ubuntu-rog2
        - ubuntu-rog3
    kube_worker:
      hosts:
        - ubuntu-rog
        - ubuntu-rog2
        - ubuntu-rog3
    etcd:
      hosts:
        - ubuntu-rog
        - ubuntu-rog2
        - ubuntu-rog3
