{{- include "kagent.rbac.validate" . -}}
{{- if .Values.rbac.namespaces }}
{{- range $namespace := .Values.rbac.namespaces | uniq | sortAlpha }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kagent.fullname" $ }}-getter-rolebinding
  namespace: {{ $namespace }}
  labels:
    {{- include "kagent.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kagent.fullname" $ }}-getter-role
subjects:
- kind: ServiceAccount
  name: {{ include "kagent.fullname" $ }}-controller
  namespace: {{ include "kagent.namespace" $ }}
{{- end }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kagent.fullname" . }}-getter-rolebinding
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kagent.fullname" . }}-getter-role
subjects:
- kind: ServiceAccount
  name: {{ include "kagent.fullname" . }}-controller
  namespace: {{ include "kagent.namespace" . }}
{{- end }}
