apiVersion: v2
name: kagent
description: A Helm chart for kagent, built with Google ADK
type: application
version: ${VERSION}
dependencies:
  - name: kmcp
    version: ${KMCP_VERSION}
    repository: oci://ghcr.io/kagent-dev/kmcp/helm
    condition: kmcp.enabled
  - name: kagent-tools
    version: 0.1.3
    repository: oci://ghcr.io/kagent-dev/tools/helm
    condition: kagent-tools.enabled
  - name: grafana-mcp
    version: ${VERSION}
    repository: file://../tools/grafana-mcp
    condition: grafana-mcp.enabled, observability-agent.enabled
  - name: querydoc
    version: ${VERSION}
    repository: file://../tools/querydoc
    condition: querydoc.enabled
  - name: k8s-agent
    version: ${VERSION}
    repository: file://../agents/k8s
    condition: k8s-agent.enabled
  - name: kgateway-agent
    version: ${VERSION}
    repository: file://../agents/kgateway
    condition: kgateway-agent.enabled
  - name: istio-agent
    version: ${VERSION}
    repository: file://../agents/istio
    condition: istio-agent.enabled
  - name: promql-agent
    version: ${VERSION}
    repository: file://../agents/promql
    condition: promql-agent.enabled
  - name: observability-agent
    version: ${VERSION}
    repository: file://../agents/observability
    condition: observability-agent.enabled
  - name: argo-rollouts-agent
    version: ${VERSION}
    repository: file://../agents/argo-rollouts
    condition: argo-rollouts-agent.enabled
  - name: helm-agent
    version: ${VERSION}
    repository: file://../agents/helm
    condition: helm-agent.enabled
  - name: cilium-policy-agent
    version: ${VERSION}
    repository: file://../agents/cilium-policy
    condition: cilium-policy-agent.enabled
  - name: cilium-manager-agent
    version: ${VERSION}
    repository: file://../agents/cilium-manager
    condition: cilium-manager-agent.enabled
  - name: cilium-debug-agent
    version: ${VERSION}
    repository: file://../agents/cilium-debug
    condition: cilium-debug-agent.enabled
  - name: oauth2-proxy
    version: "~7.0.0"
    repository: "https://oauth2-proxy.github.io/manifests"
    condition: oauth2-proxy.enabled
