{{- if and .Values.openai.apiKey (not .Values.openai.secretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "querydoc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "querydoc.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.openai.apiKey | b64enc }}
{{- end }}
