apiVersion: v1
entries:
  kube-ovn:
  - apiVersion: v2
    appVersion: 1.16.2
    created: "2026-06-29T13:32:31.784710594+08:00"
    description: Helm chart for Kube-OVN
    digest: 41256995024d1682325dc1415063ff535c19313f455178585eaa8878a5946341
    kubeVersion: '>= 1.29.0-0'
    name: kube-ovn
    type: application
    urls:
    - kube-ovn-v1.16.2.tgz
    version: v1.16.2
  longhorn:
  - apiVersion: v1
    appVersion: v1.8.1
    created: "2026-06-29T13:32:31.788399803+08:00"
    description: Longhorn is a distributed block storage system for Kubernetes.
    digest: 71cdd4d524926fc2f1587033480cf977deeb4df2fb7037f173ea8e8e6f1cdc20
    home: https://github.com/longhorn/longhorn
    icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/longhorn/icon/color/longhorn-icon-color.png
    keywords:
    - longhorn
    - storage
    - distributed
    - block
    - device
    - iscsi
    - nfs
    kubeVersion: '>=1.25.0-0'
    maintainers:
    - email: maintainers@longhorn.io
      name: Longhorn maintainers
    name: longhorn
    sources:
    - https://github.com/longhorn/longhorn
    - https://github.com/longhorn/longhorn-engine
    - https://github.com/longhorn/longhorn-instance-manager
    - https://github.com/longhorn/longhorn-share-manager
    - https://github.com/longhorn/longhorn-manager
    - https://github.com/longhorn/longhorn-ui
    - https://github.com/longhorn/longhorn-tests
    - https://github.com/longhorn/backing-image-manager
    urls:
    - longhorn-1.8.1.tgz
    version: 1.8.1
generated: "2026-06-29T13:32:31.781938154+08:00"
