#!/bin/bash
set -e

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
SCRIPTS_DIR="${TOP_DIR}/scripts"

cd ${TOP_DIR}

source ${SCRIPTS_DIR}/version

echo "Installer version: ${VERSION}"
echo "ARCH: ${ARCH}"

mkdir -p bin

LINKFLAGS="-X vdi-installer/pkg/version.Version=${VERSION}
           -X vdi-installer/pkg/version.GitCommit=${COMMIT}"

if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi

CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/vdi-installer .
