#!/bin/bash -e

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
SCRIPTS_DIR="${TOP_DIR}/scripts"
PACKAGE_VDI_REPO_DIR="${TOP_DIR}/package/vdi-cluster-repo"

source ${SCRIPTS_DIR}/version

VDI_REPO_IMAGE=rancher/vdi-cluster-repo:${VERSION}

cd ${PACKAGE_VDI_REPO_DIR}
docker build -t ${VDI_REPO_IMAGE} .

# 清理
rm -rf ${PACKAGE_VDI_REPO_DIR}/charts
