//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A2AConfig) DeepCopyInto(out *A2AConfig) {
	*out = *in
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]AgentSkill, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A2AConfig.
func (in *A2AConfig) DeepCopy() *A2AConfig {
	if in == nil {
		return nil
	}
	out := new(A2AConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarness) DeepCopyInto(out *AgentHarness) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarness.
func (in *AgentHarness) DeepCopy() *AgentHarness {
	if in == nil {
		return nil
	}
	out := new(AgentHarness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentHarness) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessChannel) DeepCopyInto(out *AgentHarnessChannel) {
	*out = *in
	if in.Telegram != nil {
		in, out := &in.Telegram, &out.Telegram
		*out = new(AgentHarnessTelegramChannelSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(AgentHarnessSlackChannelSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessChannel.
func (in *AgentHarnessChannel) DeepCopy() *AgentHarnessChannel {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessChannelCredential) DeepCopyInto(out *AgentHarnessChannelCredential) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessChannelCredential.
func (in *AgentHarnessChannelCredential) DeepCopy() *AgentHarnessChannelCredential {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessChannelCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessConnection) DeepCopyInto(out *AgentHarnessConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessConnection.
func (in *AgentHarnessConnection) DeepCopy() *AgentHarnessConnection {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessHermesSlackOptions) DeepCopyInto(out *AgentHarnessHermesSlackOptions) {
	*out = *in
	if in.AllowedUserIDs != nil {
		in, out := &in.AllowedUserIDs, &out.AllowedUserIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedUserIDsFrom != nil {
		in, out := &in.AllowedUserIDsFrom, &out.AllowedUserIDsFrom
		*out = new(ValueSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessHermesSlackOptions.
func (in *AgentHarnessHermesSlackOptions) DeepCopy() *AgentHarnessHermesSlackOptions {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessHermesSlackOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessList) DeepCopyInto(out *AgentHarnessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentHarness, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessList.
func (in *AgentHarnessList) DeepCopy() *AgentHarnessList {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentHarnessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessNetwork) DeepCopyInto(out *AgentHarnessNetwork) {
	*out = *in
	if in.AllowedDomains != nil {
		in, out := &in.AllowedDomains, &out.AllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessNetwork.
func (in *AgentHarnessNetwork) DeepCopy() *AgentHarnessNetwork {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessOpenClawSlackOptions) DeepCopyInto(out *AgentHarnessOpenClawSlackOptions) {
	*out = *in
	if in.AllowlistChannels != nil {
		in, out := &in.AllowlistChannels, &out.AllowlistChannels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InteractiveReplies != nil {
		in, out := &in.InteractiveReplies, &out.InteractiveReplies
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessOpenClawSlackOptions.
func (in *AgentHarnessOpenClawSlackOptions) DeepCopy() *AgentHarnessOpenClawSlackOptions {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessOpenClawSlackOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessSlackChannelSpec) DeepCopyInto(out *AgentHarnessSlackChannelSpec) {
	*out = *in
	in.BotToken.DeepCopyInto(&out.BotToken)
	in.AppToken.DeepCopyInto(&out.AppToken)
	if in.OpenClaw != nil {
		in, out := &in.OpenClaw, &out.OpenClaw
		*out = new(AgentHarnessOpenClawSlackOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Hermes != nil {
		in, out := &in.Hermes, &out.Hermes
		*out = new(AgentHarnessHermesSlackOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessSlackChannelSpec.
func (in *AgentHarnessSlackChannelSpec) DeepCopy() *AgentHarnessSlackChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessSlackChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessSpec) DeepCopyInto(out *AgentHarnessSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(AgentHarnessNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]AgentHarnessChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessSpec.
func (in *AgentHarnessSpec) DeepCopy() *AgentHarnessSpec {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessStatus) DeepCopyInto(out *AgentHarnessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackendRef != nil {
		in, out := &in.BackendRef, &out.BackendRef
		*out = new(AgentHarnessStatusRef)
		**out = **in
	}
	if in.Connection != nil {
		in, out := &in.Connection, &out.Connection
		*out = new(AgentHarnessConnection)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessStatus.
func (in *AgentHarnessStatus) DeepCopy() *AgentHarnessStatus {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessStatusRef) DeepCopyInto(out *AgentHarnessStatusRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessStatusRef.
func (in *AgentHarnessStatusRef) DeepCopy() *AgentHarnessStatusRef {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessStatusRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessTelegramChannelSpec) DeepCopyInto(out *AgentHarnessTelegramChannelSpec) {
	*out = *in
	in.BotToken.DeepCopyInto(&out.BotToken)
	if in.AllowedUserIDs != nil {
		in, out := &in.AllowedUserIDs, &out.AllowedUserIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedUserIDsFrom != nil {
		in, out := &in.AllowedUserIDsFrom, &out.AllowedUserIDsFrom
		*out = new(ValueSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessTelegramChannelSpec.
func (in *AgentHarnessTelegramChannelSpec) DeepCopy() *AgentHarnessTelegramChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessTelegramChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSkill) DeepCopyInto(out *AgentSkill) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Examples != nil {
		in, out := &in.Examples, &out.Examples
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InputModes != nil {
		in, out := &in.InputModes, &out.InputModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OutputModes != nil {
		in, out := &in.OutputModes, &out.OutputModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSkill.
func (in *AgentSkill) DeepCopy() *AgentSkill {
	if in == nil {
		return nil
	}
	out := new(AgentSkill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.BYO != nil {
		in, out := &in.BYO, &out.BYO
		*out = new(BYOAgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Declarative != nil {
		in, out := &in.Declarative, &out.Declarative
		*out = new(DeclarativeAgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = new(SkillForAgent)
		(*in).DeepCopyInto(*out)
	}
	if in.Sandbox != nil {
		in, out := &in.Sandbox, &out.Sandbox
		*out = new(SandboxConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = new(AllowedNamespaces)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedNamespaces) DeepCopyInto(out *AllowedNamespaces) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedNamespaces.
func (in *AllowedNamespaces) DeepCopy() *AllowedNamespaces {
	if in == nil {
		return nil
	}
	out := new(AllowedNamespaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnthropicConfig) DeepCopyInto(out *AnthropicConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicConfig.
func (in *AnthropicConfig) DeepCopy() *AnthropicConfig {
	if in == nil {
		return nil
	}
	out := new(AnthropicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnthropicVertexAIConfig) DeepCopyInto(out *AnthropicVertexAIConfig) {
	*out = *in
	in.BaseVertexAIConfig.DeepCopyInto(&out.BaseVertexAIConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicVertexAIConfig.
func (in *AnthropicVertexAIConfig) DeepCopy() *AnthropicVertexAIConfig {
	if in == nil {
		return nil
	}
	out := new(AnthropicVertexAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureOpenAIConfig) DeepCopyInto(out *AzureOpenAIConfig) {
	*out = *in
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureOpenAIConfig.
func (in *AzureOpenAIConfig) DeepCopy() *AzureOpenAIConfig {
	if in == nil {
		return nil
	}
	out := new(AzureOpenAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BYOAgentSpec) DeepCopyInto(out *BYOAgentSpec) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(ByoDeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BYOAgentSpec.
func (in *BYOAgentSpec) DeepCopy() *BYOAgentSpec {
	if in == nil {
		return nil
	}
	out := new(BYOAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseVertexAIConfig) DeepCopyInto(out *BaseVertexAIConfig) {
	*out = *in
	if in.StopSequences != nil {
		in, out := &in.StopSequences, &out.StopSequences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseVertexAIConfig.
func (in *BaseVertexAIConfig) DeepCopy() *BaseVertexAIConfig {
	if in == nil {
		return nil
	}
	out := new(BaseVertexAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockConfig) DeepCopyInto(out *BedrockConfig) {
	*out = *in
	if in.AdditionalModelRequestFields != nil {
		in, out := &in.AdditionalModelRequestFields, &out.AdditionalModelRequestFields
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockConfig.
func (in *BedrockConfig) DeepCopy() *BedrockConfig {
	if in == nil {
		return nil
	}
	out := new(BedrockConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByoDeploymentSpec) DeepCopyInto(out *ByoDeploymentSpec) {
	*out = *in
	if in.Cmd != nil {
		in, out := &in.Cmd, &out.Cmd
		*out = new(string)
		**out = **in
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.SharedDeploymentSpec.DeepCopyInto(&out.SharedDeploymentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByoDeploymentSpec.
func (in *ByoDeploymentSpec) DeepCopy() *ByoDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ByoDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextCompressionConfig) DeepCopyInto(out *ContextCompressionConfig) {
	*out = *in
	if in.CompactionInterval != nil {
		in, out := &in.CompactionInterval, &out.CompactionInterval
		*out = new(int)
		**out = **in
	}
	if in.OverlapSize != nil {
		in, out := &in.OverlapSize, &out.OverlapSize
		*out = new(int)
		**out = **in
	}
	if in.Summarizer != nil {
		in, out := &in.Summarizer, &out.Summarizer
		*out = new(ContextSummarizerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TokenThreshold != nil {
		in, out := &in.TokenThreshold, &out.TokenThreshold
		*out = new(int)
		**out = **in
	}
	if in.EventRetentionSize != nil {
		in, out := &in.EventRetentionSize, &out.EventRetentionSize
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextCompressionConfig.
func (in *ContextCompressionConfig) DeepCopy() *ContextCompressionConfig {
	if in == nil {
		return nil
	}
	out := new(ContextCompressionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextConfig) DeepCopyInto(out *ContextConfig) {
	*out = *in
	if in.Compaction != nil {
		in, out := &in.Compaction, &out.Compaction
		*out = new(ContextCompressionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextConfig.
func (in *ContextConfig) DeepCopy() *ContextConfig {
	if in == nil {
		return nil
	}
	out := new(ContextConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextSummarizerConfig) DeepCopyInto(out *ContextSummarizerConfig) {
	*out = *in
	if in.ModelConfig != nil {
		in, out := &in.ModelConfig, &out.ModelConfig
		*out = new(string)
		**out = **in
	}
	if in.PromptTemplate != nil {
		in, out := &in.PromptTemplate, &out.PromptTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextSummarizerConfig.
func (in *ContextSummarizerConfig) DeepCopy() *ContextSummarizerConfig {
	if in == nil {
		return nil
	}
	out := new(ContextSummarizerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeclarativeAgentSpec) DeepCopyInto(out *DeclarativeAgentSpec) {
	*out = *in
	if in.SystemMessageFrom != nil {
		in, out := &in.SystemMessageFrom, &out.SystemMessageFrom
		*out = new(ValueSource)
		**out = **in
	}
	if in.PromptTemplate != nil {
		in, out := &in.PromptTemplate, &out.PromptTemplate
		*out = new(PromptTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]*Tool, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tool)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.A2AConfig != nil {
		in, out := &in.A2AConfig, &out.A2AConfig
		*out = new(A2AConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(DeclarativeDeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExecuteCodeBlocks != nil {
		in, out := &in.ExecuteCodeBlocks, &out.ExecuteCodeBlocks
		*out = new(bool)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemorySpec)
		**out = **in
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = new(ContextConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeclarativeAgentSpec.
func (in *DeclarativeAgentSpec) DeepCopy() *DeclarativeAgentSpec {
	if in == nil {
		return nil
	}
	out := new(DeclarativeAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeclarativeDeploymentSpec) DeepCopyInto(out *DeclarativeDeploymentSpec) {
	*out = *in
	in.SharedDeploymentSpec.DeepCopyInto(&out.SharedDeploymentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeclarativeDeploymentSpec.
func (in *DeclarativeDeploymentSpec) DeepCopy() *DeclarativeDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeclarativeDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GDCHServiceAccountConfig) DeepCopyInto(out *GDCHServiceAccountConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GDCHServiceAccountConfig.
func (in *GDCHServiceAccountConfig) DeepCopy() *GDCHServiceAccountConfig {
	if in == nil {
		return nil
	}
	out := new(GDCHServiceAccountConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeminiConfig) DeepCopyInto(out *GeminiConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeminiConfig.
func (in *GeminiConfig) DeepCopy() *GeminiConfig {
	if in == nil {
		return nil
	}
	out := new(GeminiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeminiVertexAIConfig) DeepCopyInto(out *GeminiVertexAIConfig) {
	*out = *in
	in.BaseVertexAIConfig.DeepCopyInto(&out.BaseVertexAIConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeminiVertexAIConfig.
func (in *GeminiVertexAIConfig) DeepCopy() *GeminiVertexAIConfig {
	if in == nil {
		return nil
	}
	out := new(GeminiVertexAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepo) DeepCopyInto(out *GitRepo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepo.
func (in *GitRepo) DeepCopy() *GitRepo {
	if in == nil {
		return nil
	}
	out := new(GitRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPTool) DeepCopyInto(out *MCPTool) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPTool.
func (in *MCPTool) DeepCopy() *MCPTool {
	if in == nil {
		return nil
	}
	out := new(MCPTool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpServerTool) DeepCopyInto(out *McpServerTool) {
	*out = *in
	out.TypedReference = in.TypedReference
	if in.ToolNames != nil {
		in, out := &in.ToolNames, &out.ToolNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequireApproval != nil {
		in, out := &in.RequireApproval, &out.RequireApproval
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpServerTool.
func (in *McpServerTool) DeepCopy() *McpServerTool {
	if in == nil {
		return nil
	}
	out := new(McpServerTool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorySpec) DeepCopyInto(out *MemorySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemorySpec.
func (in *MemorySpec) DeepCopy() *MemorySpec {
	if in == nil {
		return nil
	}
	out := new(MemorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfig) DeepCopyInto(out *ModelConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfig.
func (in *ModelConfig) DeepCopy() *ModelConfig {
	if in == nil {
		return nil
	}
	out := new(ModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfigList) DeepCopyInto(out *ModelConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfigList.
func (in *ModelConfigList) DeepCopy() *ModelConfigList {
	if in == nil {
		return nil
	}
	out := new(ModelConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfigSpec) DeepCopyInto(out *ModelConfigSpec) {
	*out = *in
	if in.DefaultHeaders != nil {
		in, out := &in.DefaultHeaders, &out.DefaultHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OpenAI != nil {
		in, out := &in.OpenAI, &out.OpenAI
		*out = new(OpenAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Anthropic != nil {
		in, out := &in.Anthropic, &out.Anthropic
		*out = new(AnthropicConfig)
		**out = **in
	}
	if in.AzureOpenAI != nil {
		in, out := &in.AzureOpenAI, &out.AzureOpenAI
		*out = new(AzureOpenAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ollama != nil {
		in, out := &in.Ollama, &out.Ollama
		*out = new(OllamaConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Gemini != nil {
		in, out := &in.Gemini, &out.Gemini
		*out = new(GeminiConfig)
		**out = **in
	}
	if in.GeminiVertexAI != nil {
		in, out := &in.GeminiVertexAI, &out.GeminiVertexAI
		*out = new(GeminiVertexAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AnthropicVertexAI != nil {
		in, out := &in.AnthropicVertexAI, &out.AnthropicVertexAI
		*out = new(AnthropicVertexAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Bedrock != nil {
		in, out := &in.Bedrock, &out.Bedrock
		*out = new(BedrockConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SAPAICore != nil {
		in, out := &in.SAPAICore, &out.SAPAICore
		*out = new(SAPAICoreConfig)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfigSpec.
func (in *ModelConfigSpec) DeepCopy() *ModelConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ModelConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfigStatus) DeepCopyInto(out *ModelConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfigStatus.
func (in *ModelConfigStatus) DeepCopy() *ModelConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ModelConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderConfig) DeepCopyInto(out *ModelProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderConfig.
func (in *ModelProviderConfig) DeepCopy() *ModelProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ModelProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderConfigList) DeepCopyInto(out *ModelProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderConfigList.
func (in *ModelProviderConfigList) DeepCopy() *ModelProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(ModelProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderConfigSpec) DeepCopyInto(out *ModelProviderConfigSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderConfigSpec.
func (in *ModelProviderConfigSpec) DeepCopy() *ModelProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ModelProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderConfigStatus) DeepCopyInto(out *ModelProviderConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiscoveredModels != nil {
		in, out := &in.DiscoveredModels, &out.DiscoveredModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastDiscoveryTime != nil {
		in, out := &in.LastDiscoveryTime, &out.LastDiscoveryTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderConfigStatus.
func (in *ModelProviderConfigStatus) DeepCopy() *ModelProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ModelProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfig) DeepCopyInto(out *NetworkConfig) {
	*out = *in
	if in.AllowedDomains != nil {
		in, out := &in.AllowedDomains, &out.AllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfig.
func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OllamaConfig) DeepCopyInto(out *OllamaConfig) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OllamaConfig.
func (in *OllamaConfig) DeepCopy() *OllamaConfig {
	if in == nil {
		return nil
	}
	out := new(OllamaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIConfig) DeepCopyInto(out *OpenAIConfig) {
	*out = *in
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(int)
		**out = **in
	}
	if in.N != nil {
		in, out := &in.N, &out.N
		*out = new(int)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
	if in.ReasoningEffort != nil {
		in, out := &in.ReasoningEffort, &out.ReasoningEffort
		*out = new(OpenAIReasoningEffort)
		**out = **in
	}
	if in.TokenExchange != nil {
		in, out := &in.TokenExchange, &out.TokenExchange
		*out = new(TokenExchangeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIConfig.
func (in *OpenAIConfig) DeepCopy() *OpenAIConfig {
	if in == nil {
		return nil
	}
	out := new(OpenAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptSource) DeepCopyInto(out *PromptSource) {
	*out = *in
	out.TypedLocalReference = in.TypedLocalReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptSource.
func (in *PromptSource) DeepCopy() *PromptSource {
	if in == nil {
		return nil
	}
	out := new(PromptSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptTemplateSpec) DeepCopyInto(out *PromptTemplateSpec) {
	*out = *in
	if in.DataSources != nil {
		in, out := &in.DataSources, &out.DataSources
		*out = make([]PromptSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptTemplateSpec.
func (in *PromptTemplateSpec) DeepCopy() *PromptTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PromptTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteMCPServer) DeepCopyInto(out *RemoteMCPServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteMCPServer.
func (in *RemoteMCPServer) DeepCopy() *RemoteMCPServer {
	if in == nil {
		return nil
	}
	out := new(RemoteMCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteMCPServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteMCPServerList) DeepCopyInto(out *RemoteMCPServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteMCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteMCPServerList.
func (in *RemoteMCPServerList) DeepCopy() *RemoteMCPServerList {
	if in == nil {
		return nil
	}
	out := new(RemoteMCPServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteMCPServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteMCPServerSpec) DeepCopyInto(out *RemoteMCPServerSpec) {
	*out = *in
	if in.HeadersFrom != nil {
		in, out := &in.HeadersFrom, &out.HeadersFrom
		*out = make([]ValueRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.SseReadTimeout != nil {
		in, out := &in.SseReadTimeout, &out.SseReadTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.TerminateOnClose != nil {
		in, out := &in.TerminateOnClose, &out.TerminateOnClose
		*out = new(bool)
		**out = **in
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = new(AllowedNamespaces)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteMCPServerSpec.
func (in *RemoteMCPServerSpec) DeepCopy() *RemoteMCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteMCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteMCPServerStatus) DeepCopyInto(out *RemoteMCPServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiscoveredTools != nil {
		in, out := &in.DiscoveredTools, &out.DiscoveredTools
		*out = make([]*MCPTool, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MCPTool)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteMCPServerStatus.
func (in *RemoteMCPServerStatus) DeepCopy() *RemoteMCPServerStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteMCPServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAPAICoreConfig) DeepCopyInto(out *SAPAICoreConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAPAICoreConfig.
func (in *SAPAICoreConfig) DeepCopy() *SAPAICoreConfig {
	if in == nil {
		return nil
	}
	out := new(SAPAICoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAgent) DeepCopyInto(out *SandboxAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAgent.
func (in *SandboxAgent) DeepCopy() *SandboxAgent {
	if in == nil {
		return nil
	}
	out := new(SandboxAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAgentList) DeepCopyInto(out *SandboxAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAgentList.
func (in *SandboxAgentList) DeepCopy() *SandboxAgentList {
	if in == nil {
		return nil
	}
	out := new(SandboxAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxConfig) DeepCopyInto(out *SandboxConfig) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxConfig.
func (in *SandboxConfig) DeepCopy() *SandboxConfig {
	if in == nil {
		return nil
	}
	out := new(SandboxConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountConfig) DeepCopyInto(out *ServiceAccountConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountConfig.
func (in *ServiceAccountConfig) DeepCopy() *ServiceAccountConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedDeploymentSpec) DeepCopyInto(out *SharedDeploymentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccountName != nil {
		in, out := &in.ServiceAccountName, &out.ServiceAccountName
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccountConfig != nil {
		in, out := &in.ServiceAccountConfig, &out.ServiceAccountConfig
		*out = new(ServiceAccountConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraContainers != nil {
		in, out := &in.ExtraContainers, &out.ExtraContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedDeploymentSpec.
func (in *SharedDeploymentSpec) DeepCopy() *SharedDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(SharedDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillForAgent) DeepCopyInto(out *SkillForAgent) {
	*out = *in
	if in.Refs != nil {
		in, out := &in.Refs, &out.Refs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.GitAuthSecretRef != nil {
		in, out := &in.GitAuthSecretRef, &out.GitAuthSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.GitRefs != nil {
		in, out := &in.GitRefs, &out.GitRefs
		*out = make([]GitRepo, len(*in))
		copy(*out, *in)
	}
	if in.InitContainer != nil {
		in, out := &in.InitContainer, &out.InitContainer
		*out = new(SkillsInitContainer)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillForAgent.
func (in *SkillForAgent) DeepCopy() *SkillForAgent {
	if in == nil {
		return nil
	}
	out := new(SkillForAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillsInitContainer) DeepCopyInto(out *SkillsInitContainer) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillsInitContainer.
func (in *SkillsInitContainer) DeepCopy() *SkillsInitContainer {
	if in == nil {
		return nil
	}
	out := new(SkillsInitContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenExchangeConfig) DeepCopyInto(out *TokenExchangeConfig) {
	*out = *in
	if in.GDCHServiceAccount != nil {
		in, out := &in.GDCHServiceAccount, &out.GDCHServiceAccount
		*out = new(GDCHServiceAccountConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenExchangeConfig.
func (in *TokenExchangeConfig) DeepCopy() *TokenExchangeConfig {
	if in == nil {
		return nil
	}
	out := new(TokenExchangeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tool) DeepCopyInto(out *Tool) {
	*out = *in
	if in.McpServer != nil {
		in, out := &in.McpServer, &out.McpServer
		*out = new(McpServerTool)
		(*in).DeepCopyInto(*out)
	}
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(TypedReference)
		**out = **in
	}
	if in.HeadersFrom != nil {
		in, out := &in.HeadersFrom, &out.HeadersFrom
		*out = make([]ValueRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tool.
func (in *Tool) DeepCopy() *Tool {
	if in == nil {
		return nil
	}
	out := new(Tool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypedLocalReference) DeepCopyInto(out *TypedLocalReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypedLocalReference.
func (in *TypedLocalReference) DeepCopy() *TypedLocalReference {
	if in == nil {
		return nil
	}
	out := new(TypedLocalReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypedReference) DeepCopyInto(out *TypedReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypedReference.
func (in *TypedReference) DeepCopy() *TypedReference {
	if in == nil {
		return nil
	}
	out := new(TypedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueRef) DeepCopyInto(out *ValueRef) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueRef.
func (in *ValueRef) DeepCopy() *ValueRef {
	if in == nil {
		return nil
	}
	out := new(ValueRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueSource) DeepCopyInto(out *ValueSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueSource.
func (in *ValueSource) DeepCopy() *ValueSource {
	if in == nil {
		return nil
	}
	out := new(ValueSource)
	in.DeepCopyInto(out)
	return out
}
