apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-ovn
  namespace: kube-system
spec:
  chart: /var/lib/rancher/rke2/server/charts/kube-ovn.tgz
  targetNamespace: kube-system
  createNamespace: true
  bootstrap: true
  valuesContent: |-
    FUNC_OPTS: "--enable-mirror=false"
