apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart: /var/lib/rancher/rke2/server/charts/longhorn.tgz
  targetNamespace: longhorn-system
  createNamespace: true
  valuesContent: |-
    defaultSettings:
      defaultDataPath: "/var/lib/longhorn"
