{{- if .ServerURL }}
server: {{ .ServerURL }}
{{- end }}
token: {{ printf "%q" .Token }}
kubelet-arg:
{{- with $args := .GetKubeletArgs }}
{{- range $arg := $args }}
  - {{ printf "%q" $arg }}
{{- end }}
{{- end }}
