{{- if .ServerURL }}
server: {{ .ServerURL }}
{{- end }}
token: {{ printf "%q" .Token }}
tls-san:
  - {{ .Install.Vip }}
{{- if .SANS }}
{{- range .SANS }}
  - {{ . }}
{{- end }}
{{- end }}
cluster-cidr: {{ printf "%q" .Install.ClusterPodCIDR }}
service-cidr: {{ printf "%q" .Install.ClusterServiceCIDR }}
cluster-dns: {{ printf "%q" .Install.ClusterDNS }}
cni: none
disable:
  - rke2-ingress-nginx
kubelet-arg:
{{- with $args := .GetKubeletArgs }}
{{- range $arg := $args }}
  - {{ printf "%q" $arg }}
{{- end }}
{{- end }}
