{{- if .ServerURL }}
server: {{ .ServerURL }}
{{- end }}
token: {{ printf "%q" .Token }}
tls-san:
{{- if .Install.Vip }}
  - {{ .Install.Vip }}
{{- end }}
{{- if .SANS }}
{{- range .SANS }}
  - {{ . }}
{{- end }}
{{- end }}
{{- if not (or .Install.Vip .SANS) }}
  - 127.0.0.1
{{- end }}
cluster-cidr: {{ printf "%q" .Install.ClusterPodCIDR }}
service-cidr: {{ printf "%q" .Install.ClusterServiceCIDR }}
cluster-dns: {{ printf "%q" .Install.ClusterDNS }}
cni: none
disable:
  - rke2-ingress-nginx
kubelet-arg:
{{- with $args := .GetKubeletArgs }}
{{- range $arg := $args }}
  - {{ printf "%q" $arg }}
{{- end }}
{{- end }}
